### ISSUE TITLE
Non CSS codes

### ISSUE THREAD

**Issue by WeileiZeng** [cda-tum/qecc#81]
Nice work! just to confirm some detail.

- Does this work for Non-CSS codes? When I read the paper and codes, it mostly says Hx and Hz, which are typically for CSS codes. Does this program also work for Non-CSS codes with mixed X and Z parity checks?
- If so, would you mind giving an example of decoding the perfect five-qubit codes with shifted `XZZX` checks?

**Comment by lucasberent** [comment]
Hi, thanks for your comment. 
Currently only CSS codes are supported, since implicitly the X and Z part are decoded separately. In general the decoding can be simulated analogously for XZZX codes but this would require online updates of the error channel as far as I know, which is currently not supported.
A very nice open-source repo that supports this mechanism (with BP+OSD decoding) is: https://github.com/quantumgizmos/bias_tailored_qldpc

**Comment by WeileiZeng** [comment]
Thanks for the explanation and pointing out the other nice repo. It looks like they also only support CSS codes. 

But this is already a great tool with code construction and a decoder/distance estimator.

**Comment by lucasberent** [comment]
I believe in the corresponding paper (2202.01702) I believe it is mentioned that their bias-tailored codes (as generalization of XZZX surface codes) have equivalent stabilizers to the CSS code up to a H-rotation and thus they use the 'decoupled' decoding graph from CSS codes to decode - so I assume this is applicable to XZZX surface codes analogously. I have not looked into this in detail though. Hope it still helps!
